# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forStudents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
