# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-10 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forStudents', '0005_question_parent_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='parent_test',
        ),
    ]
