# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-10 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forStudents', '0006_remove_question_parent_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forStudents.Tests'),
            preserve_default=False,
        ),
    ]
