# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-10 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forStudents', '0007_question_parent_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.BooleanField(default=False),
        ),
    ]
