# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forStudents', '0009_choice_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
