# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forStudents', '0011_tryes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
